### ISSUE TITLE
IntOGen Plus | 2024 Release

### ISSUE THREAD

**Issue by FedericaBrando** [bbglab/intogen-plus#25]
## Pipeline
- [x] bbglab/intogen-plus#2  
- [x] bbglab/intogen-plus#4 
- [x] bbglab/intogen-plus#5 
- [x] bbglab/intogen-plus#7 
- [x] bbglab/intogen-plus#8 
- [x] bbglab/intogen-plus#9 
- [x] bbglab/intogen-plus#13
- [x] bbglab/intogen-plus#18 
- [x] bbglab/intogen-plus#19 
- [x] bbglab/intogen-plus#20
- [x] bbglab/intogen-plus#22 
- [ ] bbglab/support-backlog#214
- [ ] bbglab/intogen-plus#23 
- [x] bbglab/intogen-plus#26 
- [x] #30
- [x] IntOGen Plus | Set github repo to public

##  WEB
- [x] bbglab/support-backlog#243
- [x] IntOGen-web | Remove tables that are not expected for publishing
- [x] IntOGen-web | populate DB
- [x] IntOGen-web | Release notes
- [x] IntOGen-web | FAQ page
- [x] IntOGen-web | Set beta.intogen.org up
- [x] IntOGen-web | Check feedback and bugs
